# -*- coding: utf-8 -*-
"""FP_GROWTH.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wJCWmqs1r1Zuq12rVi4X6QpTdod7IkFU
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('/content/Market_Basket_Optimisation.csv')
df

df.info()

df.describe()

df.isnull().sum()

df.shape

for col in df.columns:
  print(df[col].name,df[col].value_counts().nunique())

from mlxtend.preprocessing import TransactionEncoder

tr =TransactionEncoder()
tr_arr = tr.fit_transform(df)

df = pd.DataFrame(tr_arr ,columns = tr.columns_)
df

from mlxtend.frequent_patterns import fpgrowth

fpgrowth(df,min_support = 0.001,use_colnames = True)

